### ISSUE TITLE
ubi8-minimal microdnf --enablerepo=ubi-8-appstream can't be used currently

### ISSUE THREAD

**Issue by Maleware** [stackabletech/docker-images#170]
The current situation for e.g. ubi8-rust-builder:
we use `FROM registry.access.redhat.com/ubi8/ubi-minimal AS builder` as base image, to install stuff we use `&& microdnf install --disablerepo=* --enablerepo=ubi-8-appstream-rpms --enablerepo=ubi-8-baseos curl findutils gcc gcc-c++ make cmake openssl-devel pkg-config systemd-devel unzip pearl -y \
  && rm -rf /var/cache/yum`
  
  This leads to the error that ubi-8-appstream is not found

**Comment by Maleware** [comment]
The problem was solved by adding `--enablerepo=ubi-8-appstream-rpms --enablerepo=ubi-8-baseos-rpms` instead of `--enablerepo=ubi-8-appstream --enablerepo=ubi-8-baseos`

**Comment by vsupalov** [comment]
The problem also does not show up if the base image is pinned to `registry.access.redhat.com/ubi8/ubi-minimal:8.6-902`

**Comment by lfrancke** [comment]
Thank you.
I'd like to understand
- why this happened
- what we need to do to fix it _now_
- what we can do to prevent it in the future if there is anything
- if this was announced somewhere (related to the previous item) so we can follow that in the future

**Comment by Maleware** [comment]
To the best of my knowledge:

- This happened because RH decided without further notice to switch their repo name from `ubi-8-appstream` to `ubi-8-appstream-rpms` . This was breaking for ubi8-rust-builder. Building product images would have worked as long as we do not touch the rust builder as it currently is
- To fix it, we can rename to `icrodnf update --disablerepo=* --enablerepo=ubi-8-appstream-rpms --enablerepo=ubi-8-baseos-rpms -y` but we do not know if and when RH decides to go back to the old thing. 
- to the best of my knowledge I haven't seen anything announcing this change, but investigating now.

**Comment by Maleware** [comment]
Fix through: https://github.com/stackabletech/docker-images/pull/171

**Comment by lfrancke** [comment]
Most of this comes from me from about a year ago and I copied it straight from the docs. Can one of you see what the docs say now?

**Comment by Maleware** [comment]
Don't think so, the documentation still states you should use ubi-8-appstream. Looks exactly like what we are doing in both links. We just use microdnf instead of yum and that's what they want us to do.

**Comment by Maleware** [comment]
Corresponiding PR: https://github.com/stackabletech/docker-images/pull/171

**Comment by Maleware** [comment]
RH suggested to look up changes here: https://access.redhat.com/articles/4238681

They claimed this being up-to-date. However, they refer in it to the old repository name and the latest update was on 31/08/22. We should be careful to rely on this.

**Comment by lfrancke** [comment]
The article was updated 20 minutes ago :)

**Comment by Maleware** [comment]
Decision:
We pin on a latest version of ubi8-minimal. Which tag we will investigate. We make it stable on this base image. We gonna Tag every operator and product image on a very specific version. 

We conclude to tag on a specific commit to avoid RH from disturbing us as good as possible.

**Comment by lfrancke** [comment]
And then we'll update that regularly?
In that case I think we should add a base image update to the release checkist maybe?

**Comment by Maleware** [comment]
I think so, but maybe I'm not the perfect one to judge on that.

**Comment by lfrancke** [comment]
Let's bring it up at the daily and ask for opinions.

**Comment by soenkeliebau** [comment]
Reopening this as the renovate config doesn't seem to have been effective and image versions are not pinned.
Will need further investigation.

**Comment by Maleware** [comment]
Pinned digests for product images: https://github.com/stackabletech/docker-images/pull/179/
Pinned digests for operator-templating: https://github.com/stackabletech/operator-templating/pull/183

**Comment by Maleware** [comment]
From the Renovate documentation, it states that it wont update a less precise version to a more precise one. I would assume that digests are as precise as it gets, so we could try to update to the exact digests we want and see if renovate can catch it now. It should work in my opinion.

**Comment by soenkeliebau** [comment]
I have so far not gotten Renovate to pin these images at all, it just ignores them.
I'll dig into it a bit more.

**Comment by Maleware** [comment]
Thanks! Don't know if could get to this today -.-

**Comment by soenkeliebau** [comment]
I've done another renovate testrun against a fork of the docker-images repo and it created a PR to pin the dependecies..
https://github.com/soenkeliebau/docker-images/pull/2/files#diff-092be6267bfa68f9f34e067d79f37fb6ce2225d225229e330aca47f90e3fd9d7R1

I don't really understand why it doesn't do it in the main repo. I didn't make any relevant changes to the renovate config I think..mostly removed the schedules to make testing easier..

paging @teozkr - if you have any ideas ..

**Comment by soenkeliebau** [comment]
fixed by #180 hopefully

**Comment by soenkeliebau** [comment]
fixed by a combination of  https://github.com/stackabletech/docker-images/pull/201 https://github.com/stackabletech/docker-images/pull/179 and https://github.com/stackabletech/docker-images/pull/180
