### ISSUE TITLE
spark-k8s and pyspark-k8s: Add s3a and abfs libs

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/docker-images#172]
S3 libs are needed for basically everything (e.g. reading/writing data and history-server) therefore we want to pre-ship them with our images.
Another reason is to put *the correct* versions in the image, as many users will be confused on which versions to put there

Implementation can be copied from hive image

- [x] Must: Libs added to new Image version. Only adding it to Spark 3.3.0 only is ok, as older Spark versions have older Hadoop versions and need other aws libs
- [ ] Must: kuttl test added
- [ ] Could: kuttl tests using s3a libs via pvcs or similar are removed
- [x] Documentation & changelog updated to mention the inclusion of these libs

**Comment by lfrancke** [comment]
I have added a point about the documentation and I'm not sure if we want to even put this in the feature tracker @soenkeliebau what do you think?

**Comment by soenkeliebau** [comment]
I'd say this is an implementation detail..no need to put it in the feature tracker.
