### ISSUE TITLE
Implement new Branch System for Docker Images

### ISSUE THREAD

**Issue by fhennig** [stackabletech/docker-images#235]
In #208 we decided to use a new branching system, to be able to update old docker images to use new base images.

In this ticket we want to implement it, and create a branch for the upcoming release. This ticket does **not** deal with new base images for older releases. Any sort of automation is also **not** part of this ticket.

## New Branching System

In the new branching system, we will maintain a **release branch per platform release**, i.e. a branch `release-22.09`, `release-22.11`.
On these branches we will tag platform versions, i.e. `22.11.0-rc1`, `22.11.0`, `22.11.1`.

As we now tag a whole platform release instead of individual products, the build system/GitHub actions should build all images from these tags.

## Acceptance Criteria

- [ ] A new branch has been made for the release 22.11
- [ ] a new tag for 22.11 release candidate 1 exists
- [ ] The GitHub action has been changed, to build images based on the new tag
- [ ] We are ready to release the 22.11 images

## Requirements

#236 Should be done first!

**Comment by lfrancke** [comment]
To me this seems like something that should at least be brought up after a daily in the team refinements.
What do you think? @soenkeliebau @fhennig

**Comment by fhennig** [comment]
Sounds like a good idea. Since a lot of people are off until wednesday, I'll just put it onto our Wednesday arch meeting agenda.

**Comment by lfrancke** [comment]
No conclusion in the Arch meeting, a followup meeting will happen, organized by @soenkeliebau

**Comment by adwk67** [comment]
Closing this issue (as agreed in the meeting/discussion on 18.11) as its contents will be covered in the scope of https://github.com/stackabletech/issues/issues/309
