### ISSUE TITLE
Update all images on the main branch

### ISSUE THREAD

**Issue by fhennig** [stackabletech/docker-images#236]
This is about updating everything on main. This is **not** about updating base images for older product images.

Some products might need to be upgraded directly, others depend on the java-base image. This needs to be upgraded.

The java-base image will need to be split, and versioned differently. Some products require Java 17, while i.e. Druid only supports java 11. The Java base image needs the latest ubi8 base image though, so we will have a java-11 base image, and a java-17 base image (at least).

## Acceptance criteria

- [x] Java base image has been split, and all new java base images use the latest ubi8 base
- [x] java based products are linked to their new respective java base image
- [x] all non-java products have been upgraded as well (airflow, opa, superset, others?)
- [x] Use newest image tags in:
  - [x] Operator repository examples
  - [x] Operator documentation
  - [x] Getting started guides
  - [x] Integration tests
  - [x] Optional: tools image in init containers

## Progress Tags

- https://github.com/stackabletech/docker-images/pull/248
- https://github.com/stackabletech/docker-images/pull/250
- https://github.com/stackabletech/docker-images/pull/251

### Products
- [x] Airflow
  - [x] 2.2.3-stackable0.4.0
  - [x] 2.2.4-stackable0.4.0
  - [x] 2.2.5-stackable0.4.0
  - [x] 2.4.1-stackable0.5.0
- [x] Druid
  - [x] 0.23.0-stackable0.2.0
  - [x] 24.0.0-stackable0.2.0
- [x] Hadoop HDFS  
  - [x] 3.2.2-stackable0.6.0
  - [x] 3.3.1-stackable0.6.0
  - [x] 3.3.3-stackable0.2.0
  - [x] 3.3.4-stackable0.2.0
- [x] HBase
  - [x] 2.4.6-stackable0.8.0
  - [x] 2.4.8-stackable0.8.0
  - [x] 2.4.9-stackable0.8.0
  - [x] 2.4.11-stackable0.8.0
  - [x] 2.4.12-stackable0.3.0
- [x] Hive
  - [x] 2.3.9-stackable0.6.0
  - [x] 3.1.3-stackable0.2.0
- [x] Kafka
  - [x] 2.7.1-stackable0.6.0
  - [x] 2.8.1-stackable0.6.0
  - [x] 3.1.0-stackable0.6.0
  - [x] 3.2.0-stackable0.2.0
  - [x] 3.3.1-stackable0.2.0
- [x] NiFi
  - [x] 1.13.2-stackable0.5.0
  - [x] 1.15.0-stackable0.5.0
  - [x] 1.15.1-stackable0.2.0
  - [x] 1.15.2-stackable0.2.0
  - [x] 1.15.3-stackable0.2.0
  - [x] 1.16.0-stackable0.2.0
  - [x] 1.16.1-stackable0.2.0
  - [x] 1.16.2-stackable0.2.0
  - [x] 1.16.3-stackable0.2.0
  - [x] 1.18.0-stackable0.2.0
- [x] pyspark-k8s
  - [x] 3.2.1-stackable0.7.0  
  - [x] 3.3.0-stackable0.3.0  
- [x] spark-k8s
  - [x] 3.2.1-stackable0.6.0  
  - [x] 3.3.0-stackable0.3.0  
- [x] Superset
  - [x] 1.3.2-stackable2.2.0
  - [x] 1.4.1-stackable2.2.0
  - [x] 1.5.1-stackable0.3.0
- [x] Trino
  - [x] 377-stackable0.2.0
  - [x] 387-stackable0.2.0
  - [x] 395-stackable0.2.0
  - [x] 396-stackable0.2.0
- [x] ZooKeeper
  - [x] 3.5.8-stackable0.8.0
  - [x] 3.6.3-stackable0.8.0
  - [x] 3.7.0-stackable0.8.0
  - [x] 3.8.0-stackable0.8.0

### Internal
- [x] OPA
  - [x] 0.27.1-stackable0.3.0
  - [x] 0.28.0-stackable0.3.0
  - [x] 0.37.2-stackable0.3.0
  - [x] 0.41.0-stackable0.2.0
  - [x] 0.45.0-stackable0.2.0
- [x] Tools
  - [x] 0.2.0-stackable0.4.0

### Products
- [x] https://github.com/stackabletech/airflow-operator/pull/193
- [x] https://github.com/stackabletech/druid-operator/pull/339
- [x] https://github.com/stackabletech/hdfs-operator/pull/271
- [x] https://github.com/stackabletech/hbase-operator/pull/275
- [x] https://github.com/stackabletech/hive-operator/pull/271
- [x] https://github.com/stackabletech/kafka-operator/pull/513
- [x] https://github.com/stackabletech/nifi-operator/pull/376
- [x] https://github.com/stackabletech/spark-k8s-operator/pull/176
- [x] https://github.com/stackabletech/superset-operator/pull/295
- [x] https://github.com/stackabletech/trino-operator/pull/340
- [x] https://github.com/stackabletech/zookeeper-operator/pull/586

### Internal
- [x] https://github.com/stackabletech/opa-operator/pull/374

**Comment by lfrancke** [comment]
When you say "upgrade" or "update" what exactly do you mean?
This is about the base images, right?

e.g. " all non-java products have been upgraded as well (airflow, opa, superset, others?)"

@soenkeliebau @fhennig

**Comment by maltesander** [comment]
All done!
