### ISSUE TITLE
Distribute Tools-Image into Product Images

### ISSUE THREAD

**Issue by Maleware** [stackabletech/docker-images#241]
With Issue https://github.com/stackabletech/issues/issues/301 we identified the operators using the tools image.

From this List we are going to distribute those tools into their corresponding product images.

### Operator to modify
 - [x] zookeeper - no change needed
- [x] hdfs - no change needed
- [x] kafka
- [x] nifi
- [x] trino
- [x] druid

**Comment by lfrancke** [comment]
The checkboxes are al ticked but the issue is not closed yet.

Is this done?
@Maleware

**Comment by Maleware** [comment]
Yes, it waits for review currently

**Comment by lfrancke** [comment]
@Maleware  I'm  sorry....what is waiting for Review exactly?

**Comment by Maleware** [comment]
This PR https://github.com/stackabletech/docker-images/pull/266/files is belongs to this ticket. @maltesander is doing the product image selection, which is needed to Test the changes. Up to that tests it is done, I think.

**Comment by Maleware** [comment]
This one: https://github.com/stackabletech/docker-images/pull/266/files

**Comment by maltesander** [comment]
duplicate of https://github.com/stackabletech/docker-images/pull/266. Closing this.
