### ISSUE TITLE
Reduce size of Docker images

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/docker-images#25]
The Docker images are much larger than the official ones:
```
$ docker images | grep trino
docker.stackable.tech/stackable/trino        362-stackable0                 4a6cc6f9f9dd   2 weeks ago     4GB
trinodb/trino                                362                            8c4c3cc8b6b5   2 months ago    1.33GB
```

The size of the images should be decreased to speed up the download. This would also make the integration tests faster and decrease the chance of hitting timeouts.

One possible optimization is to not rename the installation directory in a separate layer:
```
RUN mkdir /stackable/trino-server && \
    mv /stackable/trino-server-${PRODUCT}/* /stackable/trino-server && \
    rm -rf /stackable/trino-server-${PRODUCT}
```

**Comment by lfrancke** [comment]
See also https://github.com/stackabletech/issues/issues/149

_This_ ticket is only about fixing the immediate issue of having Docker images that are over twice the size they need to be.
There are more improvements to be made in the CI pipeline later but this is not the ticket for hat.
