### ISSUE TITLE
LTS Strategy and Upgrading older Images

### ISSUE THREAD

**Issue by adwk67** [stackabletech/docker-images#260]
## Goal

We want to implement a system that supports upgrading base images for older product images. This system should be easy to use without much repetitive manual work.

### LTS Strategy and Upgrading older Images

Do we want to upgrade base images for all previous release, all the time, indefinitely? This is to be decided. Upgrading older product images is not strictly necessary for the next release, so we decoupled this.

- [ ] #237
- [x] #238
- [x] #239

Lastly, manual steps should be automated as best we can.

**Comment by lfrancke** [comment]
Maybe some or all of this we already have now by the work @nightkr did last week

**Comment by soenkeliebau** [comment]
Closing this as the technical implementation has been taken care of by @nightkr docker bake implementation. The rest is mostly us agreeing on processes and how long we want to support things, which is handled in the linked ADR PRs.
