### ISSUE TITLE
Add hadoop-fuse to the Hadoop HDFS image

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/docker-images#341]
As a user of HDFS I want to use the HDFS fuse driver to mount HDFS in an existing Linux filesystem.

The fuse binary is not built and shipped by default by the Hadoop project. That means we'll have to build it ourselves and include it in the image.

For now, we'll include all necessary things in the normal Hadoop image. We _might_ later split it out into a separate image.

```[tasklist]
- [ ] https://github.com/stackabletech/docker-images/pull/400
- [ ] https://github.com/stackabletech/hdfs-operator/pull/375
```

**Comment by lfrancke** [comment]
This can also go into a dedicated client image if needed.

**Comment by Techassi** [comment]
I was able to build the native client via Docker. Building directly on the host is also possible, but it requires installing A LOT of dependencies manually. I haven't succeeded with that yet.

Building via Docker can be achieved like this:

#### Cloning repo

```shell
git clone git@github.com:apache/hadoop.git # This repo is quite large, 800MB ish
cd hadoop
```

#### Starting and building the Docker container

```shell
./start-build-env.sh # This takes a few hot minutes to complete
```

This creates a Docker image with all required build tools installed. It also installs most of the required dependencies. The resulting image is roughly 2.5GB big, so beware!

#### Building

After the image is built, the image is run interactively and provides a default bash shell. The building is done via this shell. The complete repo source tree is mounted inside the container and all file changes are synced between the container and the host.

```shell
mvn install -DskipTests                          # Install additional deps
cd hadoop-hdfs-project/hadoop-hdfs-native-client # MOve into the correct module dir
mvn package -Pnative -DskipTests                 # Build the module with native code
```

The jars are located in `hadoop-hdfs-project/hadoop-hdfs-native-client/target` and are named like `hadoop-hdfs-native-client-<VERSION>.jar`.

**Comment by lfrancke** [comment]
The build command is actually a bit different:

```
mvn clean package -Pnative -Drequire.fuse=true -DskipTests -Dmaven.javadoc.skip=true
```

**Comment by lfrancke** [comment]
I tested that and while the result is a binary `fuse-dfs` it refuses to run due to some shared lib errors. We first need to find out what we really need/want.

**Comment by lfrancke** [comment]
This is waiting for feedback from the customer.

**Comment by lfrancke** [comment]
Now waiting for RedHat to push `fuse-devel` to the UBI repositories: https://bugzilla.redhat.com/show_bug.cgi?id=2218035
We should also try to get this fixed upstream: https://issues.apache.org/jira/browse/HDFS-16930
