### ISSUE TITLE
Images are fairly large, can we shrink them a bit?

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/docker-images#346]
We received feedback that our product images are fairly large and have been asked to investigate if this can be reduced with reasonable effort.

The operators are fine, this is just in reference to the product images.

Specifically mentioned were:
- NiFi
- Druid
- Trino

For this specific use case Trino would be the most important one to have a look at.

**Comment by soenkeliebau** [comment]
edited the issue text

**Comment by nightkr** [comment]
Vector is one relatively low-hanging fruit, currently we use the official kitchensink build, but rebuilding the same version with a more minimal setup (file source, elastic sink, remap transformer) gets us down to 56MiB.

**Comment by nightkr** [comment]
Letting this go for now, just wanted to put some numbers on the table.

**Comment by lfrancke** [comment]
Yeah, it doesn't seem too bad. I looked at Trino as well and that's just large in itself.
There is probably a bit we can trim but it won't be much.

We already did a round of optimizations in the past here.

**Comment by lfrancke** [comment]
What we should do however is something in the PR templates for docker-images to check if the size increases by a change.

**Comment by soenkeliebau** [comment]
One thing we could do is offer images with the archives in them instead of an extracted product and then unpack this at startup... not sure if that would save anything though, I presume docker images themselves are compressed as well...

**Comment by nightkr** [comment]
^, plus even at best we're just trading (cheap) disk space for (expensive) RAM by doing that.

**Comment by fhennig** [comment]
Hey that sounds neat. Not sure how that would be generated, but seeing it listed like that makes me feel more understanding

**Comment by soenkeliebau** [comment]
Not sure what @nightkr used to generate the stats above, but at a guess it'll be a bit specific per repo. My mental eye sees a shell script per image that we then either run when building the image and store the output as a text file that Antora then pulls in, or run it as part of the docs build process ..

**Comment by lfrancke** [comment]
I have evaluated most images and while they can be improved they are also not bad.
As part of generating SBOMs we're moving all docker images to use builder tasks and remove redundant packages.
I'll close this because it's not very actionable in itself.
