### ISSUE TITLE
Add HBCK2 to the HBase images

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/docker-images#359]
https://github.com/apache/hbase-operator-tools
https://hbase.apache.org/downloads.html

Unfortunately, we need to make sure that the version the operator tools are compiled for matches the HBase version itself.
I think it makes sense to include this directly in the HBase image but a separate client image would also work

**Comment by siegfriedweber** [comment]
added to the HBase image in stackabletech/docker-images#497
documented in stackabletech/hbase-operator#416
