### ISSUE TITLE
Include async-profiler v2 into the HDFS & HBase images

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/docker-images#532]
This allows users to start a _profile_ run for those tools from the Web UI which makes it much easier for support staff and administrators to diagnose performance issues.

Part of this work will be [upstreamed](https://issues.apache.org/jira/browse/HBASE-28242) at HBase but only for the upcoming 3.x version.
We still need to propose the same changes to the HDFS project.

The current work can be found in the `SUP-56` branch.

Tasks left to do (might be incomplete):
- [x] Add a test which checks whether the profiler servlet is available (only 200/404 status check)
- [x] Remove hardcoded version numbers
- [x] Mirror the async-profiler binary to our own repository
- [x] Remove workarounds to make the images compatible with 23.7

**Comment by siegfriedweber** [comment]
Pull requests:

* stackabletech/docker-images#540
* stackabletech/hdfs-operator#465
* stackabletech/hbase-operator#445

**Comment by lfrancke** [comment]
I'm wondering if this is something we should document anywhere.
We could have a `Troubleshooting` section in the docs...

Opinions?

**Comment by siegfriedweber** [comment]
In my opinion, the burden of creating and maintaining the documentation outweighs the usefulness of the profiler.

The main benefit of the profiler is probably to show the absence of a problem rather than its presence.
