### ISSUE TITLE
Include AWS jars in HBase image

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/docker-images#557]
This allows using ExportSnapshot to copy snapshots directly to S3.

The following JARs are required in the HBase image to be able to run the command.
They are coming from Hadoop itself and are not bundled by default in HBase.
We should depend on the Hadoop image and copy them over:

- /stackable/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-1.12.262.jar  
- /stackable/hadoop/share/hadoop/tools/lib/hadoop-aws-3.3.4.jar

Afterwards this command can be used:

```shell
/stackable/hbase/bin/hbase org.apache.hadoop.hbase.snapshot.ExportSnapshot \
            -D fs.s3a.endpoint=https://s3gateway.url/ \
            -D fs.s3a.access.key=ABCD12345 \
            -D fs.s3a.secret.key=08154711 \
            -D fs.s3a.connection.ssl.enabled=false \
            -snapshot s_OMID_TIMESTAMP_TABLE_20240212_095025 \
            -copy-from hdfs://dev1-hdfs/hbase \
            -copy-to s3a://bucketname/tmp/ -mappers 16
```

## Acceptance criteria

- [ ] HBase image contains all required JARs to `ExportSnapshot` to S3, these do not necessarily need to be in the HBase classpath by default but they need to be in the HBase image
- [ ] A convenience bash script to call `ExportSnapshot` which includes the correct classpath

Notes: The script does not need to do much, it is enough if it basically contains `/stackable/hbase/bin/hbase org.apache.hadoop.hbase.snapshot.ExportSnapshot` so one doesn't have to remember the name of the class and if the JARs are not on the classpath by default it should also amend the classpath used.

**Comment by sbernauer** [comment]
Just for the record: Please document them the same way as spark does it: https://github.com/stackabletech/docker-images/blob/a05caee2e504d1eeab2d079b969891d48539db9b/conf.py#L252-L253

**Comment by lfrancke** [comment]
Thank you, I'll take a look!
