### ISSUE TITLE
Move SBOM and signing to image tools

### ISSUE THREAD

**Issue by Maleware** [stackabletech/docker-images#598]
## Current Situation
We have SBOM's and signing within our workflow in GH. We have a build script which should do those things as it handles all product builds within.

## Wanted Situation
`bake` can sign and generate sbom's

**Comment by lfrancke** [comment]
Why would we want that? What's the benefit of `bake` doing it?

**Comment by Maleware** [comment]
My thought was about consistency. I think it's better to have all functionality we have being handled by one tool instead of multiple places to change/update/fix things.

**Comment by lfrancke** [comment]
Well....yes. I think docker includes experimental support for SBOM generation. I'd rather control it myself.

@dervoeti please comment but I'd be in favor of closing this. I don't think we want to do this.

**Comment by dervoeti** [comment]
Yeah, I tried generating and signing SBOMs with docker, but there were multiple problems. For details see this comment:
https://github.com/stackabletech/issues/issues/512#issuecomment-1927621802 ("Further approaches")

**Comment by Maleware** [comment]
@dervoeti means we can close it? :)

**Comment by lfrancke** [comment]
I think so, yes. Unless you object?

**Comment by Maleware** [comment]
Happy to do so :)
