### ISSUE TITLE
Remove unnecessary dependencies from our images

### ISSUE THREAD

**Issue by dervoeti** [stackabletech/docker-images#627]
To reduce the potential attack surface and thus the number of vulnerabilities in our images, we should try to remove all unnecessary dependencies.

The basic idea is to look for dependencies that are not really needed at runtime and remove them.
Some vague examples:
 - Unneeded JAR files
 - System packages (maybe set `install_weak_deps=0` option for microdnf?)
 - Packages that are needed for features that are never enabled in our platform

A good place to start might be to browse through critical vulnerabilities in SecObserve, inspect the components are affected by them and verify if they are really needed. Or to think about general options / techniques to clean up our images.

**Comment by lfrancke** [comment]
We already do set the settings to not install week dependencies. This is in the base image

**Comment by dervoeti** [comment]
Closing this as this was part of the vulnerability hackathon (my main concerns were adressed in https://github.com/stackabletech/docker-images/pull/665 and https://github.com/stackabletech/operator-templating/pull/361). We'll remove further unnecessary dependencies if we find some during vulnerability analysis, I don't think we need a general issue for this anymore.
