### ISSUE TITLE
Add renovate to this repository

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/docker-images#63]
and remove dependabot

**Comment by RishiKumarRay** [comment]
@soenkeliebau can you provide any documentation for implementation ? i want to try this

**Comment by soenkeliebau** [comment]
You should pretty much be able to simply copy the config from any of the operators repositories.

For example here: https://github.com/stackabletech/kafka-operator/blob/main/renovate.json
Regarding dependabot, it should be as easy as removing the config from this repo: https://github.com/stackabletech/docker-images/blob/main/.github/dependabot.yml

**Comment by RishiKumarRay** [comment]
@soenkeliebau please assign me

**Comment by soenkeliebau** [comment]
Done.

While you are at it, this ticket has a sister and a brother, if you have the time :)

https://github.com/stackabletech/product-config/issues/53
https://github.com/stackabletech/integration-tests/issues/173

**Comment by RishiKumarRay** [comment]
@soenkeliebau sure i will try to do that too , you can assign me that too

**Comment by soenkeliebau** [comment]
fixed by #171
