### ISSUE TITLE
Spark: Add the HBase connector to the image

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/docker-images#870]
Add the [Apache HBase™ Spark Connector](https://github.com/apache/hbase-connectors/tree/master/spark) to the image, so that Spark applications can access HBase.

The connector must be compiled for a specific HBase version. It must be tested, if choosing the current LTS version (2.4.18) also works with the other supported versions, i.e. 2.6.0.

- [x] #878 
- [x] #882
- [x] stackabletech/spark-k8s-operator#471

**Comment by lfrancke** [comment]
Do we have docs for this? If so, could you link to them? And could you include a snippet that we can use in the release notes?

**Comment by siegfriedweber** [comment]
> Do we have docs for this?

No, we don't. I am not sure if it makes sense to document how to use HBase within a Spark application. This is not SDP specific. However, it could be useful to list the capabilities of our product images in the documentation, but I am not aware that we did this already.

> And could you include a snippet that we can use in the release notes?

## Release Notes

### Other product features

* Apache Spark: [Apache HBase Spark Connector](https://github.com/apache/hbase-connectors/tree/master/spark) added
